apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lookit.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{- define "lookit.inlineconfigs" }}
nginx.conf: |-
  user nginx;
  worker_processes 1;

  pid /var/run/nginx.pid;

  error_log /var/log/nginx/error.log warn;

  events {
      worker_connections 1024;
  }

  http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      log_format main '$remote_addr - $upstream_cache_status $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
                      'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
      access_log /var/log/nginx/access.log main;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 620s;
      keepalive_requests 10000;
      types_hash_max_size 2048;
      server_tokens off;

      gzip on;
      gzip_disable "MSIE [1-6]\.(?!.*SV1)";
      gzip_comp_level 2;
      gzip_min_length 512;
      gzip_proxied any;
      gzip_vary on;
      gzip_types text/plain
                 text/css
                 image/svg+xml 
                 application/javascript
                 application/x-javascript
                 text/xml
                 application/xml
                 text/javascript
                 application/json
                 application/xml+rss
                 application/vnd.api+json;

      server {
          listen {{ .Values.web.service.internalPort }};
          keepalive_timeout 620s;
          root /static/code;
          client_max_body_size 25M;
          server_name _;
          
          if ($http_x_forwarded_proto = "http") {
              return 301 https://$host$request_uri;
          }

          location = /healthz {
              access_log off;
              return 200;
          }

          location = /robots.txt {
              alias /usr/share/nginx/html/robots.txt;
          }

          {{- if .Values.configEnvs.MEDIA_URL }}
          location /media/ {
              proxy_redirect off;
              proxy_buffering off;
              proxy_pass {{ .Values.configEnvs.MEDIA_URL }};
          }
          {{- else }}
          # location /media/ {
          #     alias /media/;
          # }
          {{- end }}

          location /favicon.ico {
              rewrite ^/(.*)$ /static/$1;
          }

          {{- if .Values.configEnvs.STATIC_URL }}
          location /static/ {
              proxy_redirect off;
              proxy_buffering off;
              proxy_pass {{ .Values.configEnvs.STATIC_URL }};
          }
          {{- else }}
          location /static/ {
              alias /static/;
          }
          {{- end }}

          location / {
              # Disable caching of application requests
              add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate";
              add_header Expires "Mon, 01 Jan 1990 00:00:00 GMT";
              add_header Pragma "no-cache";

              # Pass requests to uwsgi application
              include /etc/nginx/uwsgi_params;
              uwsgi_buffering off;
              uwsgi_request_buffering off;
              uwsgi_pass uwsgi://127.0.0.1:{{ .Values.web.service.externalPort }};
          }
      }
  }
{{- end -}}
{{- range $key, $value := .Values.configEnvs }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key, $value := merge .Values.configFiles (include "lookit.inlineconfigs" . | fromYaml) ((.Files.Glob "files/*").AsConfig | fromYaml) }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
