enabled: true

ember:
  nameOverride: osf-preprints
  replicaCount: 1
 
  image:
    repository: quay.io/centerforopenscience/osf-preprints
    tag: develop
    pullPolicy: Always

  resources: {}

  nginx:
    image:
      repository: nginx
      tag: alpine
      pullPolicy: Always

    resources: {}

  configFiles: {}
