# Default values for barman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: centerforopenscience/barman
  tag: '9.6'
  pullPolicy: Always

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

persistence:
  enabled: true
  # storageClass: ssd
  accessMode: ReadWriteOnce
  size: 8Gi

backups:
  # see more: http://docs.pgbarman.org/release/2.3/#examples-of-configuration
  default:
    schedule: 0 1 * * *
    conf: |-
      [default]
      description =  "Example of PostgreSQL Database (Streaming-Only)"
      conninfo = host=pg user=barman dbname=postgres password=guessme
      streaming_conninfo = host=pg user=streaming_barman password=guessme
      backup_method = postgres
      streaming_archiver = on
      slot_name = barman

      ; see more @ http://docs.pgbarman.org/release/2.3/barman.5.html#options
      ; retention_policy = REDUNDANCY 999
  # another:
  #   schedule: 0 1 * * *
  #   conf: |-
  #     ; Barman, Backup and Recovery Manager for PostgreSQL
  #     ; http://www.pgbarman.org/ - http://www.2ndQuadrant.com/
  #     ;
  #     ; Template configuration file for a server using
  #     ; only streaming replication protocol
  #     ;

  #     [default]
  #     ; Human readable description
  #     description =  "Example of PostgreSQL Database (Streaming-Only)"

  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     ; PostgreSQL connection string (mandatory)
  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     conninfo = host=pg user=barman dbname=postgres password=guessme

  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     ; PostgreSQL streaming connection string
  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     ; To be used by pg_basebackup for backup and pg_receivexlog for WAL streaming
  #     ; NOTE: streaming_barman is a regular user with REPLICATION privilege
  #     streaming_conninfo = host=pg user=streaming_barman password=guessme

  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     ; Backup settings (via pg_basebackup)
  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     backup_method = postgres
  #     ;streaming_backup_name = barman_streaming_backup

  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     ; WAL streaming settings (via pg_receivexlog)
  #     ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  #     streaming_archiver = on
  #     slot_name = barman
  #     ;streaming_archiver_name = barman_receive_wal
  #     ;streaming_archiver_batch_size = 50

  #     ; PATH setting for this server
  #     ;path_prefix = "/usr/pgsql-9.6/bin"

  #     ; Policy for retention of periodic backups and archive logs.
  #     ; If left empty, retention policies are not enforced.
  #     ;retention_policy = REDUNDANCY 999

configFiles: {}
