apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "cerebro.fullname" . }}
  labels:
    app: {{ template "cerebro.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "cerebro.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: cerebro
        env:
        - name: JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.heapSize }} -Xmx{{ .Values.heapSize }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 9000
          name: http
        volumeMounts:
        - mountPath: /opt/cerebro/conf/application.conf
          name: secret
          subPath: application.conf
        {{- if .Values.tls.enabled }}
        {{- if hasKey .Values.tls "files" }}
        {{- range $key := keys .Values.tls.files }}
        - mountPath: /certs/{{ $key }}
          name: secret
          subPath: certs-{{ $key }}
          readOnly: true
        {{- end }}
        {{- end }}
        {{- if hasKey .Values.tls "base64Files" }}
        {{- range $key := keys .Values.tls.base64Files }}
        - mountPath: /certs/{{ $key }}
          name: secret
          subPath: certs-{{ $key }}
          readOnly: true
        {{- end }}
        {{- end }}
        {{- end }}
      volumes:
      - name: secret
        secret:
          secretName: {{ template "cerebro.fullname" . }}
