apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }} 
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{- end }} 
  ports:
# CUSTOM START
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.externalPort }}
# CUSTOM END
    protocol: TCP
    name: http
  selector:
    app: {{ template "jenkins.name" . }}
    component: {{ .Values.master.name }}
    release: {{ .Release.Name }}
