apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- include "osf.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - gosu
        - www-data
        - invoke
        - celery_worker
        - --hostname
        - worker.%h
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: 'api.base.settings'
        - name: LOG_PATH
          value: /log
        - name: UPLOADS_PATH
          value: /uploads
        - name: ANALYTICS_PATH
          value: /analytics
        {{- include "osf.dbSettings" . | indent 8 }}
        volumeMounts:
        - mountPath: /log
          name: log-volume
        - mountPath: /uploads
          name: uploads-volume
        - mountPath: /analytics
          name: analytics-volume
        {{- include "osf.volumeMounts" . | indent 8 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: uploads-volume
        emptyDir: {}
      - name: analytics-volume
        emptyDir: {}
      {{- include "osf.volumes" . | indent 6 }}
