apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "osf.deploymentAnnotations" . | indent 8 }}
    spec:
      initContainers:
      - name: uwsgi-static
        image: "{{ .Values.uwsgi.image.repository }}:{{ .Values.uwsgi.image.tag }}"
        imagePullPolicy: {{ .Values.uwsgi.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - mkdir -p /static/code/api &&
          cp -Rf /code/api/static /static/code/api
        volumeMounts:
        - mountPath: /static
          name: static-volume
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        command:
        - nginx
        - -c
        - /nginx/nginx.conf
        - -g
        - daemon off;
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 10
        volumeMounts:
        - mountPath: /static
          name: static-volume
        - mountPath: /nginx/nginx.conf
          name: config-volume
          subPath: nginx.conf
          readOnly: true
        - mountPath: /nginx/robots.txt
          name: config-volume
          subPath: robots.txt
          readOnly: true
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}
      - name: uwsgi
        image: "{{ .Values.uwsgi.image.repository }}:{{ .Values.uwsgi.image.tag }}"
        imagePullPolicy: {{ .Values.uwsgi.image.pullPolicy }}
        command:
        - uwsgi
        - --ini
        - /etc/uwsgi/uwsgi.ini
        - --socket
        - :{{ .Values.service.externalPort }}
        env:
        {{- include "osf.dbSettings" . | indent 8 }}
        ports:
        - name: wsgi
          containerPort: {{ .Values.service.externalPort }}
        - name: stats
          containerPort: 1717
        volumeMounts:
        - mountPath: /etc/uwsgi/uwsgi.ini
          name: config-volume
          subPath: uwsgi.ini
          readOnly: true
        {{- include "osf.volumeMounts" . | indent 8 }}
        resources:
{{ toYaml .Values.uwsgi.resources | indent 10 }}
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}
      {{- include "osf.volumes" . | indent 6 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}